version: '1.0'

services:
  app:
    image: node:lts
    container_name: theme_js
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: 3000
